### ISSUE TITLE
@apply .container;

### ISSUE THREAD

**Issue by ConsoleTVs** [tailwindcss/tailwindcss#407] opened 2018-03-02 19:19 UTC
```
`@apply` cannot be used with .container because .container is included in multiple rulesets.
```

Is there a way to solve this or it must never be injected using apply?

**Comment by adamwathan** [comment] 2018-03-02 19:22
Right now `@apply` is only designed to work for simple single-definition classes that aren't part of media queries and don't include any pseudo selectors.

Duplicate of https://github.com/tailwindcss/tailwindcss/issues/298.

**Closed by adamwathan** 2018-03-02 19:22 UTC

**Comment by ConsoleTVs** [comment] 2018-03-02 19:23
Sorry for the duplicate adam!
