### ISSUE TITLE
Add outline support

### ISSUE THREAD

**Issue by HapLifeMan** [tailwindcss/tailwindcss#87] opened 2017-11-03 17:01 UTC
Can you add `outline` property?
It's very useful when building forms to have an `outline: none;` attribute :)

**Comment by psren** [comment] 2017-11-03 17:07
Dupe of https://github.com/tailwindcss/tailwindcss/issues/56#issuecomment-341765853

**Comment by reinink** [comment] 2017-11-03 17:33
Duplicate indeed. Closing this in favour of #56.

**Closed by reinink** 2017-11-03 17:33 UTC
