### ISSUE TITLE
@apply error when using a class name that's the same as a HTML element (eg: table or blockquote)

### ISSUE THREAD

**Issue by samuelgoddard** [tailwindcss/tailwindcss#870] opened 2019-04-25 14:51 UTC
This is a pretty random bug that you might not actually be interested in fixing, just thought it was worth mentioning incase anyone else runs into anything similar. I previously discussed this with `@jalendport` on Discord.

Basically when using a class name that matches a HTML element and using `@apply`, i get an error due to (i think) it trying to assign itself to itself... for example:

```
.table {  
  @apply bg-red;
}

.pretty-tables {
  table {
    @apply .table;
  }
}
```

would throw the error:

```
(36:5) `@apply` cannot be used with .table because .table is included in multiple rulesets.
```

I looked into this error message and found a few other bugs that throw this error when using complicated base classes with media queries / pseudos etc, but in my case i'm doing nothing complex at all.

Changing the `.table` class to something like `.tble` or `.tablebase` works fine

I've tested this with a few other things such as `.blockquote` and `blockquote` and getting the same results

I'm using Tailwind v1 with PostCSS and Webpack

**Comment by Nerderer** [comment] 2019-04-25 20:32
Isn't this because Tailwind already has a .table class defined?

https://tailwindcss.com/docs/display

**Comment by adamwathan** [comment] 2019-04-26 13:31
I can't replicate this with `.blockquote`, but the reason it is happening with `.table` is because there is already a `.table` class in Tailwind, so the error is correct since you are adding a second class with the same name.

This compiles fine for me:
![image](https://user-images.githubusercontent.com/4323180/56811131-07b67000-6806-11e9-92f9-9b0e7e248792.png)


Can you create a project that reproduces the issue using `blockquote`?

**Comment by adamwathan** [comment] 2019-04-27 15:13
Closing this since it makes sense why it happens with `.table` and I can't reproduce with `.blockquote`. If someone can create a reproduction happy to look at it!

**Closed by adamwathan** 2019-04-27 15:13 UTC

**Comment by samuelgoddard** [comment] 2019-04-29 08:06
@adamwathan Tried again with blockquote and the previous example I had working (or broken) seems to be fine now so must've been user error! Sorry for wasting your time, thanks for investigating this :)
