### ISSUE TITLE
[ISSUE] Purge CSS  - Remove responsive and hover css class

### ISSUE THREAD

**Issue by alexgilbertDG** [tailwindcss/tailwindcss#391] opened 2018-02-19 16:34 UTC
I'm using Gulp to create a build folders. I'm using basic html template and css files with tailwind css 
@tailwind preflight; and @tailwind utilities; . When I try to purge all unused css classes, my output is working fine until i'm using responsive, hover classes (hover:, md:, lg:). So I think the issue is that the html class is md: and the css classes is md\\: because css need to escape :

Maybe there is a option in my gulp file to make those two value equal.

There's my gulp config:

`

    return gulp.src(['./css/main.css'])
    
        .pipe(postcss([
            tailwindcss('./tailwind.js'),
            require('autoprefixer'),
            require('postcss-flexibility') // make the display: -js flexibility trick for old browser // https://github.com/7rulnik/postcss-flexibility
        ]))
        .pipe(purgecss({
            content: ["index.html"],
            extractor: class TailwindExtractor {
                static extract(content) {
                  return content.match(/[A-z0-9-:\/]+/g) || [];
                }
              }
        }))
        .pipe(cleanCSS({compatibility: 'ie8'}))
        .pipe(concat('main.min.css'))
        .pipe(gulp.dest('./css'));

`

I try using without  the extractor class and it's the same thing.

Thanks

Version:
  "devDependencies": {
    "gulp-clean-css": "^3.9.0",
    "gulp-concat": "^2.6.1",
    "postcss-flexibility": "^2.0.0",
    "tailwindcss": "^0.4.1"
  },
  "dependencies": {
    "connect": "^3.6.5",
    "gulp-clean": "^0.4.0",
    "gulp-htmlmin": "^4.0.0",
    "gulp-purgecss": "^0.20.0",
    "gulp-uglify": "^3.0.0",
    "purgecss-from-html": "^1.0.0",
    "serve-static": "^1.13.1"
  }
Node: 6.6.0

**Comment by adamwathan** [comment] 2018-02-19 16:43
Hmm this should be handled by this commit to Purgecss from last November:

https://github.com/FullHuman/purgecss/commit/c99e597d2e49dc07b1b327399be6bd0ae11f882e

I can't reproduce it here, but either way this would be something to bring up as an issue on the Purgecss repo rather than here.

Going to close this as not a Tailwind issue, but if you want to share a small repository that reproduces this behavior I'm still happy to help troubleshoot.

**Closed by adamwathan** 2018-02-19 16:43 UTC

**Comment by alexgilbertDG** [comment] 2018-02-19 17:30
Go checkout this repo, simple gulp file with two versions of the same css, one purge, one not. The purge one don't work.
[https://github.com/alexgilbertDG/TailwindcssTest](https://github.com/alexgilbertDG/TailwindcssTest)

Thanks for the support ! I will open a issue on the purgecss repo if we can fix this simple repo.

**Comment by tlgreg** [comment] 2018-02-20 09:45
Seems like the issue is in the options.
`extractor` should be `extractors` (plural) and it should be an array of extractor objects, like so:
```js
// ...
.pipe(purgecss({
    content: ["index.html"],
    extractors: [
        {
            extractor: TailwindExtractor,
            extensions: ['html']
        }
    ]
}))
```

**Comment by alexgilbertDG** [comment] 2018-02-20 14:23
Thanks so much ! I just updated my repo with a working version, If tailwind want to shared it in the documentation  [https://tailwindcss.com/docs/controlling-file-size](https://tailwindcss.com/docs/controlling-file-size)(Because right now there's no gulpfile doc) I got no problem with that.

**Comment by aparajita** [comment] 2018-02-20 15:09
You might also want to use [purgecss-from-html](https://github.com/FullHuman/purgecss-from-html) as the extractor.

```js
const purgeHtml = require('purgecss-from-html');

purgecss({
  content: ['*.html'],
    extractors: [
    {
      extractor: purgeHtml,
      extensions: ['html'],
    }
  ]
})
```

**Comment by mwidmann** [comment] 2019-05-16 09:55
Sorry, if I post in this closed issue @adamwathan , but using the configuration settings in https://tailwindcss.com/docs/controlling-file-size#setting-up-purgecss the purged css is missing all the responsive styles. I thus updated the config to look like this and it works. 

```js
const purgecss = require('@fullhuman/postcss-purgecss')({
  ...
  extractors: [
    {
      extractor: class TailwindExtractor {
        static extract(content) {
          return content.match(/[A-Za-z0-9-_:\/]+/g) || []
        }
      },
      extensions: ['css', 'html', 'vue'],
    },
  ],
  // defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
}
```

my full postcss.config.js looks like this for a nuxt.js project:

```js
const purgecss = require('@fullhuman/postcss-purgecss')({
  // Specify the paths to all of the template files in your project
  content: ['./layouts/**/*.vue', './components/**/*.vue', './pages/**/*.vue'],
  whitelist: ['html', 'body'],

  extractors: [
    {
      extractor: class TailwindExtractor {
        static extract(content) {
          return content.match(/[A-Za-z0-9-_:\/]+/g) || []
        }
      },
      extensions: ['css', 'html', 'vue'],
    },
  ],
})

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    ...(process.env.NODE_ENV === 'production' ? [purgecss] : []),
  ],
}
```

**Comment by CvX** [comment] 2019-05-16 11:25
@mwidmann what's your purgecss version? The `defaultExtractor` option used in the documentation has been added [version 1.3.0](https://github.com/FullHuman/purgecss/releases/tag/v1.3.0).

**Comment by mwidmann** [comment] 2019-05-16 11:48
I had version 1.1.0 (=latest) of @fullhuman/postcss-purgecss installed, but that came with purgecss@1.1.0 and had the issue. 

I ran `npm i -D @fullhuman/postcss-purgecss@1.1.0` and now I have purgecss@1.3.0 installed and it works now.

**Comment by CvX** [comment] 2019-05-16 11:51
Btw. the latest version of `@fullhuman/postcss-purgecss` is 1.2.0: https://www.npmjs.com/package/@fullhuman/postcss-purgecss?activeTab=versions

That version specifically updates the `purgecss` dependency to 1.3.0. 🙂

**Comment by mwidmann** [comment] 2019-05-16 11:53
I was looking in the github repository and there the latest release was 1.1.0 https://github.com/FullHuman/postcss-purgecss/releases. So many sources to check.... :)

**Comment by jakedowns** [comment] 2020-12-16 18:57
glad i found this thread, it was helpful in retaining my responsive tailwind classes with purgecss in prod.

if anyone is using purgecss/@fullhuman/postcss-purgecss: `^3.1.0-alpha.0` 

the extractor class implementation changed slightly:

```
extractors: [
          {
            extractor: (content)=>{
              // fix for escaped tailwind prefixes (sm:, lg:, etc)
              return content.match(/[A-Za-z0-9-_:\/]+/g) || []
            },
            extensions: ['css', 'html', 'vue'],
          },
        ],
```

trying to think of how i'd modify this regex to retain classes with important in them, like: `md:!mt-12` => `.md\:\!mt-12`
