### ISSUE TITLE
Utility first suggestion for .active classes

### ISSUE THREAD

**Issue by incompletude** [tailwindcss/tailwindcss#562] opened 2018-09-30 05:34 UTC
Hey guys, thank you for all the hard work. I'm loving tailwind and the utility first approach.

I'm having trouble putting my head around a utility first approach to active classes like the following one. 

Any suggestions?

```html
                    <div class="hnav-button">
                        <span class="hnav-button__bar"></span>
                        <span class="hnav-button__bar"></span>
                    </div>
```

```css
.hnav-button {
    cursor: pointer;

    display: flex;
    flex-direction: column;
    align-items: flex-end;
}

.hnav-button__bar {
    width: 24px;
    height: 2px;
    margin-bottom: 6px;
    background-color: #3a3e3a;
    transform-origin: top right;
    transition: all 200ms linear;

    &:last-of-type {
        width: 16px;
        margin-bottom: 0;
        transform-origin: bottom right;
    }
}

.hnav-button.active .hnav-button__bar {
    width: 25px;
    background-color: #63d488;

    &:first-of-type {
        margin-bottom: 15px;
        transform: rotate(-45deg);
    }

    &:last-of-type {
        transform: rotate(45deg);
    }
}
```

**Comment by adamwathan** [comment] 2018-10-01 13:29
Closing this since not a bug or anything with Tailwind, use the [Discuss](https://github.com/tailwindcss/discuss) repo instead for questions like this 👍 

Quick answer is if you want to be able to add an `active` class or similar to an element and have the styles change, that's the sort of thing you could do when [creating your own component classes](https://tailwindcss.com/docs/extracting-components) by extending Tailwind with your own custom CSS.

A pure utility approach would be to just change the classes that are applied based on whether the item is active or not.

In VueJS that might look like this for example:

```
<nav>
  <a href="/home" :class="[ isActive('home') ? 'font-bold text-blue' : 'text-grey-dark']">...</a>
  <a href="/about" :class="[ isActive('about') ? 'font-bold text-blue' : 'text-grey-dark']">...</a>
  <a href="/contact" :class="[ isActive('about') ? 'font-bold text-blue' : 'text-grey-dark']">...</a>
</nav>
```

**Closed by adamwathan** 2018-10-01 13:29 UTC

**Comment by incompletude** [comment] 2018-10-01 23:50
<div class="z-10 lg:none">
                    <div class="group flex flex-col items-end cursor-pointer">
                        <span class="w-px-24 h-px-2 mb-px-6 bg-dark-gray transform-origin-tp group-active:mb-px-15 group-active:w-px-25 group-active:-rotate-45 group-active:bg-green t-all t-fast t-linear"></span>
                        <span class="w-px-16 h-px-2 bg-dark-gray transform-origin-br group-active:w-px-25 group-active:rotate-45 group-active:bg-green t-all t-fast t-linear"></span>
                    </div>
                </div>

thx

**Comment by lowbits** [comment] 2021-01-20 08:58
@incompletude how did you achieve the group-active can you share your code? Would be formidable
