### ISSUE TITLE
[1.0.0-beta.5] Can't access padding/height from theme

### ISSUE THREAD

**Issue by MichaelDeBoey** [tailwindcss/tailwindcss#869] opened 2019-04-25 13:05 UTC
When having the following `tailwind.config.js` (I'm using the  `padding` key in the `theme`  function)
```js
module.exports = {
  theme: {
    container: theme => ({
      center: true,
      padding: theme('padding.4'),
    }),
  },
  variants: {},
  plugins: [],
}
```
I get the following CSS for the `container` class
```css
.container {
  width: 100%;
  margin-right: auto;
  margin-left: auto;
}
```

When I change my config to using the `spacing` key
```diff
  container: theme => ({
    center: true,
-   padding: theme('padding.4'),
+   padding: theme('spacing.4'),
  }),
```
The CSS is what I expected to be
```diff
  .container {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
+   padding-right: 1rem;
+   padding-left: 1rem;
  }
```

I don't know if this is intended, but it seems weir to talk about `spacing` when I want to get a `padding` value (think about when I added a new one that's not in the  `spacing` range for example)

**Comment by adamwathan** [comment] 2019-04-26 15:49
Yeah just had a stab at this and I'm not sure this is going to be possible, at least not by someone who isn't much smarter than me.

The problem is that `theme('padding')` is defined as a function since it depends on `spacing`, so `padding.4` is undefined until the theme is fully resolved. We'd have to figure out a way to deterministically flatten all of the functions as much as possible before evaluating any `theme` calls so that `padding` was actually an object by the time you tried to inspect it.

**Comment by MichaelDeBoey** [comment] 2019-04-26 16:22
Hmmmm seems a tough one I think, since that function can have other `theme('whatever')` calls, which can be functions again, and so on, ... 😕

**Comment by adamwathan** [comment] 2019-04-26 16:36
Yeah really complicated to solve for sure. Best solution in the interim be to just throw an explicit error to let the user know what's going on, but even that is sort of hard because given `theme('padding.4')` returns undefined, we'd have to know that `theme('padding')` is a function to give the user the right error. And if we are able to determine that's a function, we should be able to resolve the `4` by invoking the function. The hard part is getting the string `padding` out of `padding.4`, because the user could also pass `padding[4]`, and there could be dots in other places too like `foo[bar.baz]`. Would have to see how lodash does it internally.

It's *probably* solvable but it's hard.

**Comment by MichaelDeBoey** [comment] 2019-04-26 16:41
Everything _is_ solvable if you believe in yourself 😉

Not a real pain to access it via `spacing` in my case, but I can imagine that people with an extended `padding` (which can be a function too btw, no?) want to access those values for instance...

**Comment by adamwathan** [comment] 2019-05-14 12:00
Does this work the way you'd expect now @MichaelDeBoey?

**Comment by MichaelDeBoey** [comment] 2019-05-14 13:14
This seems to work with normal values
```js
// working.js
module.exports = {
  theme: {
    container: theme => ({
      center: true,
      padding: theme('padding.4'),
    }),
  },
  variants: {},
  plugins: [],
};
```

But not when extending
```js
// not-working.js
module.exports = {
  theme: {
    extend: {
      height: {
        88: `calc(${theme('height.64')} + ${theme('height.24')})`,
      },
    },
  },
  variants: {},
  plugins: [],
};
```
Then I get the following error:
```sh
🚫 RangeError: Maximum call stack size exceeded
```

**Comment by CvX** [comment] 2019-05-14 13:58
It fails because the `extend` section gets merged into the default theme.
Your example is essentially equal to this:

```js
theme: {
  height: theme => ({
    88: `calc(${theme('height.64')} + ${theme('height.24')})`,
  })
}
```

So, `height` needs `height` to resolve, hence the infinite loop.

We should define exactly how we want the `theme()` resolution to work.
For example, should this be a valid case?

```js
theme: {
  height: theme => ({
    1: theme('height.2'),
    2: theme('height.3'),
    3: '3rem',
  })
}
```

Should we detect actual circular dependencies?
```js
{
  height: theme => ({
    1: theme('height.1'),
  })
}
```

**Comment by adamwathan** [comment] 2019-05-14 14:01
I'm comfortable with it not working for even circular-ish dependencies (like referencing any other height value inside of height) honestly, but if it's possible to make more scenarios work that's always great.

**Comment by MichaelDeBoey** [comment] 2019-05-14 14:06
I understand why it's not working, but since I'm explicitly _extending_, I think it's also logical to use the `theme('height.4')` call instead of `theme('spacing.4')`

**Comment by adamwathan** [comment] 2019-05-18 19:56
Going to close this as "fixed as much as I think is reasonable to fix" but if we can make it even smarter that's great. For now I'm okay with the current behavior.

**Closed by adamwathan** 2019-05-18 19:56 UTC
