### ISSUE TITLE
minified CSS File Size 140+kb despite PurgeCSS

### ISSUE THREAD

**Issue by UIX-Design** [tailwindcss/tailwindcss#860] opened 2019-04-22 11:56 UTC
Before you open an issue, please check if a similar issue already exists or has been closed before.

**Describe the bug**
Despite using `postcss` and `purgecss`, my minified `.min.css` 148KB is large, down from 440KB. The Coverage Tab inside the Chrome Dev Tools says, that i have 96% unused styles in my `.min.css` file:

<img width="1139" alt="Bildschirmfoto 2019-04-22 um 12 47 08" src="https://user-images.githubusercontent.com/48715009/56497180-d0da1480-64fc-11e9-9ccf-9c71bc811c6c.png">

My gulpfile task looks like this:

```js
var sass = require('gulp-sass'),
      autoprefixer = require('autoprefixer'),
      plumber = require('gulp-plumber'),
      sourcemaps = require('gulp-sourcemaps'),
      postcss = require('gulp-postcss'),
      tailwindcss = require('tailwindcss'),
      cssnano = require('cssnano'),
      purgecss = require('@fullhuman/postcss-purgecss'),
      rename = require('gulp-rename'),
      browserSync = require('browser-sync');

var src = './src/',
    dist = './dist/'

class TailwindExtractor {
    static extract(content) {
        return content.match(/[A-Za-z0-9-_:/]+/g) || [];
    }
}

gulp.task('sass', done => {
    gulp.src(src + 'assets/sass/**/*.scss')
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(sass({
            includePaths: ['node_modules']
        }))
        .pipe(postcss(
            [
                tailwindcss(src + 'tailwind.config.js'),
                autoprefixer(),
                cssnano({
                    preset: 'default',
                }),
                purgecss({
                    content: [src + '**/*.html'],
                    css: [src + 'assets/sass/uix.scss'],
                    extractors: [{
                        extractor: TailwindExtractor,
                        extensions: ['html']
                    }]
                }),
            ],
        ))
        .pipe(rename({ suffix: '.min' }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest(dist + 'assets/css'))
        .pipe(browserSync.stream());
    done();
});
```

The strucutre of my `sass` folder looks like this:

```
-- src
     -- assets
          -- sass 
               -- uix.scss
               -- _home.scss
```
My `uix.scss` looks like this:

```scss
@tailwind base;
@tailwind components;

@import 'home';

@tailwind utilities;
```

My `_home.scss` looks like this:

```scss
body {
    @apply bg-black-base m-0 p-0;
}

img {
    max-width: none;
    display: unset;
    height: 100%;
}

::-webkit-scrollbar {
    display: none;
}

.macbook {
    @screen xxl {
        width: 1032px;
        height: 607.08px;
    }
}
...
```

And my `*.html` files looks like this in terms of css-classes:

```html
<div class="w-full flex items-center justify-center flex-col">
    <div data-lax-opacity="0 1, (document.body.scrollHeight*0.1) 0" class="lax text-center container px-4 mb:px-10 mt-32 500:mt-10">
        <h1 class="text-white text-3xl">This is a headline</h1>
        <p class="text-bluegray-base font-light mt-1">This is a paragraph</p>
    </div>
</div>
```

**Software Versions**
 - OS: macOS
- Version of Tailwindcss: v1.0.0 Beta 4
 - Version of Purgecss: 1.1.0

Why is the CSS file so large and how can I best fix the problem?
Thanks for your help

**Comment by rowild** [comment] 2019-04-22 12:08
@UIX-Design I recently read something about purgeCss not recognizing classes that use back slashes or colors or @ etc. There is a little bit of discussion going on here:
https://github.com/FullHuman/purgecss/issues/15
Could this probably be the cause?

**Comment by adamwathan** [comment] 2019-04-22 12:32
Had a look at your actual project, the problem comes from having screens that are named as numbers.

You have screens called `400`, `500`, and `960`, which creates classes like:

```css
.\34 00\:appearance-none { ... }
```

...because the number need to be escaped since a CSS class can't start with a number. Purgecss seems to not handle these properly, likely just a bug/edgecase that they have not accounted for.

If you rename those screen sizes to start with a letter, you'll see you get the results you'd expect.

I'm going to try and reproduce the issue in a test case for Purgecss and see if it's straightforward to fix, but going to close this as "can't fix on our end" since not a Tailwind issue.

**Closed by adamwathan** 2019-04-22 12:32 UTC
