### ISSUE TITLE
tailwind.com website not opening up.

### ISSUE THREAD

**Issue by abhinav098** [tailwindcss/tailwindcss#1588] opened 2020-04-18 15:25 UTC
I'm trying to load tailwind: https://tailwindcss.com/

but the website is not loading up. What's the issue ?

**Comment by narwy** [comment] 2020-04-18 22:53
The website loads fine, looks like an issue on your end.

**Comment by abhinav098** [comment] 2020-04-19 08:27
Yeah, thanks for confirming, It's now working fine, yesterday it was not loading. You can close this issue.

**Comment by florianbouvot** [comment] 2020-04-19 09:50
@abhinav098 I think you can close it to 😀

**Closed** 2020-04-19 09:52 UTC

**Comment by abhishek00678** [comment] 2023-08-13 10:14
when i click onny live preview its is not loading nor any componet loading i dont understand what the issue is
