### ISSUE TITLE
Changing "whitelist" in purge options to "safelist"

### ISSUE THREAD

**Issue by jmhungdev** [tailwindcss/tailwindcss#1886] opened 2020-06-06 07:15 UTC
In light of BLM, I think we can do better in the naming space. I am proposing to change, instead of using the word "whitelist," use "safelist," when setting up tailwind.config.js.

Here's a screenshot from TailwincCSS docs in how to add the "whitelist" option in tailwind.config.js to use the purge feature.

<img width="727" alt="Screen Shot 2020-06-06 at 1 44 18 AM" src="https://user-images.githubusercontent.com/10273125/83938129-9fbbb280-a797-11ea-9c39-5eb5e5bc076e.png">

I assume TailwindCSS inherits PurgeCSS naming convention for using the word whitelisting, which is fine, but since it is implemented under the hood, I think TailwindCSS has an opportunity to change that.

This issue is inspired by this tweet:
<img width="595" alt="Screen Shot 2020-06-06 at 1 45 56 AM" src="https://user-images.githubusercontent.com/10273125/83938558-0c847c00-a79b-11ea-93a8-6b0bf9721add.png">

**Comment by adamwathan** [comment] 2020-06-06 10:35
Duplicate of #1868.

**Closed by adamwathan** 2020-06-06 10:35 UTC
