### ISSUE TITLE
[Feature Proposal] Resolve function keys recursively

### ISSUE THREAD

**Issue by limitlessloop** [tailwindcss/tailwindcss#1007] opened 2019-07-05 15:24 UTC
It would be useful to be able to reference values from `config.theme` no matter how many levels deep they are referenced from.

Below are some use cases:

When using a custom plugin to text styles which are a group of CSS declarations grouped together.

```js
textStyle: {
  heading: {
    fontFamily: theme => theme("fontFamily.body"),
    lineHeight: "1.4",
    letterSpacing: "-0.3em",
    fontWeight: "500"
  },
  link: {
    fontFamily: theme => theme("fontFamily.body"),
    lineHeight: "1.4",
    letterSpacing: "-0.3em"
  }
  // more styles
}
```

Or creating a plugin which allows you to apply colour themes but you would like to reference which is the default.

```js
colorTheme: {
  default: theme => theme("color.theme.light"),
  light: {
    color: "#000000",
    backgroundColor: "#FFFFFF",
    headingColor: "red",
    linkColor: "pink"
  }
}
```

Or simply when trying to alias values in other situations.

I had a look in the source code and I can see that `resolveFunctionKeys` in https://github.com/tailwindcss/tailwindcss/blob/master/src/util/resolveConfig.js is responsible for dealing with the above and can see it only looks at the first property key-value pair.

I had a play around with it but I couldn't get the object to return correctly and I wasn't sure how to do it recursively, I could only do it a set number of levels.

I think this would be a valuable addition if possible.

What are your thoughts?

**Comment by CvX** [comment] 2019-07-05 15:31
(This issue is a continuation of the discussion started in #869)

**Comment by AlexVipond** [comment] 2019-07-05 15:41
@limitlessloop what about `theme('fontFamily').body` or `theme('color').theme.light` - does that work for your use case?

**Comment by limitlessloop** [comment] 2019-07-05 16:42
Hi @AlexVipond, can you expand a bit more on what you mean? Or show an example? Thanks.

**Comment by AlexVipond** [comment] 2019-07-05 16:57
`theme('fontFamily')` returns the object stored in the `fontFamily` key of your theme. So, if you're configuring a different plugin and you want to access `fontFamily.body`, which I'm assuming is an array of font names (Strings), you can just do `theme('fontFamily').body` instead of `theme('fontFamily.body')`

**Comment by limitlessloop** [comment] 2019-07-05 17:04
@AlexVipond Thanks for your reply.

No that's not quite the issue I'm experiencing. The issue is that  `theme => theme("foo")` can only be used one level deep into the theme config.

You can do:

```js
theme {
    foo: "green",
    bar: theme => theme("foo")
}
```

But you can't do:
```js
theme {
    foo: "green",
    bar: {
        baz: theme => theme("foo")
    }
}
```
because functions are only resolved one level deep.

I can resolve the functions further than one level, but I'm not smart enough to return it as the correct and valid object at this [point](https://github.com/tailwindcss/tailwindcss/blob/b800a69e48e9873f391906471bcadd76aef14fd4/src/util/resolveConfig.js#L56) because it gets a bit complicated for me to understand. From what I can tell at this point it checks each first level key-value to see if the value is a function or not. If it's a function it "resolves" it into a value. It doesn't check to see if it's object however and then look again to see if it's key-value is a function. Sorry for my poor explanation.

**Comment by AlexVipond** [comment] 2019-07-05 17:14
Ahh gotcha, understood.

In that case, at least for your examples, you can still define a top level function that returns an object using the `them` function inside. 

```
textStyle: theme => ({
  heading: { 
    fontFamily: theme("fontFamily").body,
    lineHeight: "1.4",
    letterSpacing: "-0.3em",
    fontWeight: "500"
  },
  link: {
    fontFamily: theme("fontFamily").body,
    lineHeight: "1.4",
    letterSpacing: "-0.3em"
  },
  // More styles
})
```

That should get all the proper values in place, and then it's up to the plugin to generate classes given that config structure of nested objects

**Comment by limitlessloop** [comment] 2019-07-05 17:18
Yes, thanks for that, I think I did have something like that at one point. Although I'm not sure it will  work for the second example with the colour theme because the styles being referenced by `default` would be inside the theme function. It also gets quite hard to read.

**Comment by AlexVipond** [comment] 2019-07-05 18:43
Yep applying the same concept to the color theme example would be a circular dependency and wouldn't work.

Taking a step back, I'm curious to know if you've considered composing component classes using `@apply` instead of solving this using plugins? E.g.

```
.heading {
  @apply font-body font-500;
  line-height: 1.4,
  letter-spacing: -0.3em;
}
```

**Comment by limitlessloop** [comment] 2019-07-05 19:19
I have but I'd like to keep all design choices abstracted from the stylesheets.

**Comment by AlexVipond** [comment] 2019-07-05 20:09
Makes sense. I looked at the color example again, here's an alternate solution:

```
colorTheme: () => {
  const light = {
    color: "#000000",
    backgroundColor: "#FFFFFF",
    headingColor: "red",
    linkColor: "pink"
  }

  return { default: light, light }
}
```

I think given the choice between writing a bit more vanilla JS in my config vs. using a more magical `theme` function, I prefer vanilla JS

**Comment by limitlessloop** [comment] 2019-07-05 21:24
@AlexVipond thanks. I think it's extremely useful to know ways to implement these ideas using more native methods, just by following your examples I'm learning so much.

I was however very close to getting something working in my own local project and so I persisted and I believe I was able to get the desired functionality work so I have submitted a pull request for anyone to take a look through, although my code is probably not the prettiest.

**Comment by adamwathan** [comment] 2019-07-05 21:54
This is a bit of a tricky one because I know of at least one case of using functions nested in your theme config for purposes *other* than this, for example the Tailwind custom forms plugin allows you to define your SVG icons as functions so they can receive your configured icon color:

```js
  theme: {
    customForms: theme => ({
      default: {
        checkbox: {
          icon: iconColor => '<svg fill="${iconColor}" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>',
          iconColor: theme('colors.gray.800'),
          '&:hover': {
            iconColor: theme('colors.gray.700'),
          },
        },
      },
    })
  },
```

Making all nested function values be evaluated as if they are top level functions would break this, although maybe it's possible to update the forms plugin to still work by traversing the theme that's passed in and extracting the icon color.

In general I worry it's hard/impossible to make all this stuff work perfectly when you have properties that are referencing themselves, but maybe it can be done? Don't really have a strong opinion on what to do here yet although I lean towards keeping things the way they are and recommending Alex's suggestion of creating a variable, if only to avoid changing things or making anything any more complicated.

**Comment by limitlessloop** [comment] 2019-07-05 23:00
Forgive me if I've misunderstood, but your example shows nested functions. Would allowing a user to use a function further down the tree effect this? Wouldn't nested functions continue to work as normal in your example? Anyway, I appreciate it is tricky and not straight forward. I did a quick test with your example above and it seemed to still output the same with my changes, but I don't know how to write a unit test for this to be sure.

Feel free to review what I've submitted.

**Comment by AlexVipond** [comment] 2019-07-06 00:38
@limitlessloop The key detail in Adam's nested functions is that they accept custom arguments. For example, the function assigned to `icon` takes `iconColor` as the first argument. His plugin is specially designed to pass these arguments.

If tailwind tried to resolve _all_ nested functions by passing `theme` as the first argument, it would break these custom functions that are designed by plugin creators to take a different first argument.

One solution to that problem is to force all plugin creators to follow a specific pattern that plays nice with the resolveConfig function.

I think in the end this all becomes a question of tradeoffs:
- Resolving nested `theme` functions is super useful in some plugin cases, but restricting and possibly confusing/unexpected in other cases.
- Resolving nested `theme` functions/making it more magical might make the API more palatable for new users, but would also introduce complexity into the codebase, potentially dissuading newcomers from tinkering and contributing

I think both the pros and cons are not super extreme in this case, so I also don't have a strong opinion, although I mean toward keeping things the same. Definitely gonna go read your related PR though and see if that changes my mind!

**Comment by limitlessloop** [comment] 2019-07-07 13:04
Sorry, I don't understand. I'm not sure what nested functions have to do with what I'm prosing and also what you mean by passing `theme` as the first argument.

All I'm suggesting is that instead of stopping at the first level to execute the `theme => {}` function you continue until you reach a value.

I believe the only change I've made in the pull request is to keep looking at each level of the config to check for the `theme => {}` function and the original source code runs as normal.

So what I'm suggesting isn't to have a more magical API but more to correct its behaviour. In my opinion, if you're going to create something bespoke or customised as appears to be the way it is now, then keeping the functionality basic doesn't necessarily make it more intuitive, in fact, it does the opposite. 

I tried to run the example using the Tailwinds Custom Forms but it wasn't working for me on a fresh install of Tailwind. The value of `${iconColor}` didn't output the colour it was referencing even before I made my proposed code changes, so I'm not able to test if it changes work with it yet. As it stands my changes output the same as what it did before.

**Comment by adamwathan** [comment] 2019-07-07 13:28
The problem is that some plugins (like the custom forms plugin) already allow you to use a function for some of the configuration. If we implement what you propose, Tailwind itself will invoke those functions thinking they are lazily evaluated blocks that expect to receive the `theme` argument, even though they are not, they are custom functions that the plugin plans to invoke itself in some way.

The custom forms plugin has an option like this that allows a function:

```
icon: iconColor => '<svg fill="${iconColor}" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>',
```

If we implement this feature, Tailwind will invoke that function and pass through `theme` instead of `iconColor`, breaking the plugin.

Hope that makes sense. Again it's not impossible to rework the custom forms plugin to work under these conditions but there is a lot to consider.

**Comment by limitlessloop** [comment] 2019-07-07 14:26
I'll have to look at your plugin to see if I can understand better what you're describing. Like I said when I tried your plugin with a fresh install it wasn't working correctly for me anyway. I'll have to try again and create an issue. In you plugin doesn't your custom function come after the theme function anyway? I'm really confused but maybe that's just because of my lack of experience coding.

**Comment by limitlessloop** [comment] 2019-07-08 15:21
Hi, I tested the custom forms plugin and as thought, I can't get the SVG example to work correctly. I'm just linking the issue here for reference.

https://github.com/tailwindcss/custom-forms/issues/23

**Comment by limitlessloop** [comment] 2019-07-08 22:36
Hi, so I just wanted to update this issue to let you know that my suggestion isn't breaking your plugin.

These two examples can coexist.

```js
colorTheme: {
  default: theme => theme("colorTheme.light"),
  light: {
    color: "#000000",
    backgroundColor: "#FFFFFF",
    headingColor: "red",
    linkColor: "pink"
  }
},
customForms: theme => ({
  default: {
    checkbox: {
      icon: iconColor =>
        `<svg fill="${iconColor}" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>`,
      iconColor: theme("colors.gray.800"),
      "&:hover": {
        iconColor: theme("colors.gray.700")
      }
    }
  }
})
```

**Comment by AlexVipond** [comment] 2019-07-09 03:18
@limitlessloop cool, nice work on this so far. Does the example below work too? I.e. passing a normal config object to the custom forms plugin:

```
colorTheme: {
  default: theme => theme("colorTheme.light"),
  light: {
    color: "#000000",
    backgroundColor: "#FFFFFF",
    headingColor: "red",
    linkColor: "pink"
  }
},
customForms: {
  default: {
    checkbox: {
      icon: iconColor =>
        `<svg fill="${iconColor}" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" ><path d="M0 11l2-2 5 5L18 3l2 2L7 18z"/></svg>`,
      iconColor: 'gray',
      "&:hover": {
        iconColor: 'gray'
      }
    }
  }
}
```

**Comment by limitlessloop** [comment] 2019-07-09 11:13
@AlexVipond ah yes, that's a better example because in that scenario it doesn't work because of the reasons you and Adam have described above.

There are a couple of ways to solve for that:

1. Detect the names of the parameters and evaluate as necessary. This would be useful to do both for resolving a theme value lookup and for custom plugins, however, I'm not sure on the reliability of detecting parameter names as you would have to convert the function to a string. I've tested it with a basic function that searches for `theme` as the parameter and it prevents the custom forms plugin from breaking.  It would work alright for the majority of cases although may break on more complicated inputs.

2. Some sort of way to serialise the config and provide a way for plugins to utilise this to do what they want. For example, add a list of functions to the config which a plugin can then look for and the plugin can execute these functions.

There are probably some other things that can be done to improve this as well, although I don't think it's enough to restrict resolving theme value lookups to the top level, it's not intuitive and if other plugins use the same technique to resolve their own functions, they may also cause compatibility issues. It would be better to think about this problem sooner rather than later in my opinion because as plugins grow it will mean any improvement you make to the way functions are handled inside the config will require all plugins to be updated.

If it is decided that theme references have to be resolved at the top level then we could also document this.

**Comment by adamwathan** [comment] 2019-07-09 11:26
I'm going to say no to this at least for now, because it introduces a lot of extra complexity.

I would recommend solving the problems in the original post by either:

1. Using the theme function only at the top-level if you only need to reference values from other sections of the config.
    
    ```js
    textStyle: theme => ({
      heading: {
        fontFamily: theme("fontFamily.body"),
        lineHeight: "1.4",
        letterSpacing: "-0.3em",
        fontWeight: "500"
      },
      link: {
        fontFamily: theme("fontFamily.body"),
        lineHeight: "1.4",
        letterSpacing: "-0.3em"
      }
      // more styles
    })
    ```

2. Declaring any values that are needed multiple times in a single section as variables local to a function defined for that section:


    ```js
    colorTheme: () => {
      const light = {
        color: "#000000",
        backgroundColor: "#FFFFFF",
        headingColor: "red",
        linkColor: "pink"
      }

      return { default: light, light }
    }
    ```

Very much appreciate the thought put into the suggestion though, hope this isn't too disappointing.

**Closed by adamwathan** 2019-07-09 11:26 UTC

**Comment by limitlessloop** [comment] 2019-07-09 12:05
Hi @adamwathan no that's fine. I understand your reasoning for not wanting to implement it. It took me a while to realise the problem you were getting at because the original example you provided wasn't an accurate use case, so that frustrated me a bit.

I also think it should be made clearer in the documentation that `theme()` will only work if the function is defined at the top level.
