### ISSUE TITLE
Issue in Chrome with font weights (maybe a Chrome bug)

### ISSUE THREAD

**Issue by darrylhein** [tailwindcss/tailwindcss#1402] opened 2020-02-27 23:16 UTC
I've noticed that in Chrome 81+ (tried 80 (80.0.3987.116), 81 (81.0.4044.34), and 82 (82.0.4056.3)) on MacOS, the font weights are all showing as normal even though they have different weights in CSS. Here's a screenshot from the Tailwind website (Chrome 81 MacOS):

<img width="701" alt="Font Weights" src="https://user-images.githubusercontent.com/376976/75487551-d2216c80-596b-11ea-8ec3-ebdbb8634620.png">

If I remove `system-ui,-apple-system,BlinkMacSystemFont` from the font stack then they have different weights. I've tried on my computer and Browserstack so I'm fairly confident it's not font issue on my computer. It does seem fine on Windows in Chrome and all other browsers on MacOS.

My guess is this is a bug in Chrome or some Chrome/MacOS issue, but I thought I'd post here just in case someone else runs into it and maybe I can save them some time. Or...maybe someone has some insight.

This maybe the same/similar issue as #1394 but I could be wrong.

**Comment by adamwathan** [comment] 2020-03-02 14:21
Super weird! Definitely seems like a Chrome bug, going to escalate to my contacts there.

**Comment by darrylhein** [comment] 2020-03-02 15:39
Interesting: just tried Chrome 82 and the weights are showing up again there. Maybe just a bad few builds. But still broken in 81.

**Comment by argyleink** [comment] 2020-03-02 17:03
Sup y'all, bummer discovery! Thanks for reporting it. :+1:  

I've done some investigation and ultimately put most the thoughts into this Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1057654. 

@darrylhein, Chrome 82 latest didnt resolve the issue for me, so I'm wondering what I need to do differently in order to see what you see? Having it fixed in 82 would be great, as it would allow me to find the offending commit by working backwards. You're just using Canary to test 82 yeah?

**Comment by darrylhein** [comment] 2020-03-02 17:09
@argyleink I was trying in Browserstack. It's running 82.0.4056.3. But I just tried on my local machine running 82.0.4075.0 and no font weights.

**Comment by argyleink** [comment] 2020-03-03 16:29
Catalina font update caused it. "Looks like the issue only occurs for SF NS Display, i.e. font sizes > 16, when the display variant is used." A solution is known, engineering on top of it 👍

**Comment by adamwathan** [comment] 2020-03-11 13:03
Closing since Chrome bug and being fixed. Thanks @argyleink!

**Closed by adamwathan** 2020-03-11 13:03 UTC

**Comment by bramus** [comment] 2020-04-15 12:15
> A solution is known, engineering on top of it 👍

@argyleink: What is the solution (other than simply not using `BlinkMacSystemFont`)? Now that Chrome 81 has been released about a week ago many websites are affected by this. Bug is still present in Canary (Chrome 84).

**Comment by argyleink** [comment] 2020-04-15 14:28
The bug is of very high priority internally and is marked as a Chrome 83 blocker, aka required for 83 releasing. While it may still reproduce in Canary, I'm confident 83 will include resolution. 

Here's a [temporary solution](https://bugs.chromium.org/p/chromium/issues/detail?id=1057654#c35) until then, so you get some weights back in the meantime. 

I've got projects affected by this too, and yeah, the Chromium team is on it.

**Comment by damirkotoric** [comment] 2020-04-25 03:06
Thank you for the temporary workaround but I hope this can be fixed properly ASAP.

**Comment by darrylhein** [comment] 2020-04-25 03:48
I believe this may be resolved. In Chrome 83.0.4103.23, I'm now seeing the font weights on Tailwind's docs. I believe it was the latest update the fixed the issue, but I'm not sure if I missed an update or not.

<img width="488" alt="Screen Shot 2020-04-24 at 9 47 36 PM" src="https://user-images.githubusercontent.com/376976/80270435-3c594380-8675-11ea-82a2-6e2a1e3265f3.png">

**Comment by adamwathan** [comment] 2020-04-25 13:20
Unfortunately not resolved, we just switched to a different font for now so the docs weren't confusing.

**Comment by bramus** [comment] 2020-04-25 13:29
@darrylhein To work around this issue you can remove the use of `BlinkMacSystemFont` and replace it with the Inter font family, which is a drop-in replacement for SF Pro.

I've [detailed and implemented this my blog](https://www.bram.us/2020/04/24/chrome-vs-blinkmacsystemfont-a-workaround/). Here's a diff of my CSS:

```diff
+ @import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');

…

- font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", 'Inter', "Helvetica Neue", sans-serif;
+ font-family: -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", 'Inter', "Helvetica Neue", sans-serif;
```

**Comment by lxmfly123** [comment] 2022-04-29 04:50
Using Chrome v100, still cannot display bold Chinese without remove "BlinkMacSystemFont"

**Comment by jeremiahlateef** [comment] 2022-08-24 08:56
I still have this same issue in my Chrome browser, Version 104.0.5112.102. The font-weight and the font-size do not reflect on browser but I can see them both in the dev tools. Any idea what the issue may be? I'm on a Windows btw.

**Comment by rankmartin** [comment] 2023-01-25 12:29
Problem in Chrome browser still exists.

A possible solution is to change the name of the font and leave the src value at "local" empty. Works for me!

In the input.css:
`/* nunito-700 - latin */
@font-face {
font-family: 'CustomNunito';
font-style: normal;
font-weight: 700;
src: local(''),
    url('./../fonts/nunito-v25-latin/nunito-v25-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
    url('./../fonts/nunito-v25-latin/nunito-v25-latin-700.woff2') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}`

In the tailwind.config.js:
`fontFamily: {
      'nunito': ['CustomNunito', 'Helvetica', 'Arial', 'sans-serif'],
}`
