### ISSUE TITLE
Ability To @apply md:pr-sm lg:pr-lg

### ISSUE THREAD

**Issue by riiccardo** [tailwindcss/tailwindcss#1440] opened 2020-03-12 20:19 UTC
@adamwathan @tailwindcss

thanks for your great utils
how to use apply with `separator`

``` scss

.selector {
   @apply md:pr-sm lg:pr-md md:rtl:text-right md:ltr:text-left lg:flex sm:block hover:bg-black
   @apply md\:pr-sm lg\:pr-md md\:rtl\:text-right md\:ltr\:text-left lg\:flex sm\:block hover\:bg-black
}

```

<del>I getting error with ` : ` separator</del>

<del> I test both codes above </del>

can we use this kinda @apply ?

#1044

**Comment by riiccardo** [comment] 2020-03-12 20:23
or with `tailwindcss-dir`
``` scss

.selector {
   @apply rtl:text-right ltr:text-left
}

```

**Comment by riiccardo** [comment] 2020-03-12 21:13
https://tailwindcss.com/course/composing-utilities-with-apply/#app

ok I got it

but that was cool stuff if that's work tho ✋

**Comment by adamwathan** [comment] 2020-03-22 17:27
Duplicate of #313

**Closed by adamwathan** 2020-03-22 17:27 UTC
