### ISSUE TITLE
Can't use pseudo class in utility

### ISSUE THREAD

**Issue by jlurena** [tailwindcss/tailwindcss#1888] opened 2020-06-06 15:02 UTC
Hi,

Not sure if this isn't supported or not but seems tailwind ignores my utility classes.

Say I have the following plugin function:

```js
plugin(({ addUtilities, config }) => {
  const buttons = {
    '.btn': {
      padding:           '.5rem 2rem',
      'text-decoration': 'none',
      'min-width':       config('theme.minWidth.button'),
      'text-align':      'center',
      'border-radius':   config('theme.borderRadius.button-primary'),
      '&:hover': {
         'background-color': 'red'
       }
    },
    '.primary': {
      'background-color': config('theme.colors.brand-color'),
      color:              config('theme.colors.white'),
      border:             `2px solid ${config('theme.colors.brand-color')}`
    }
  };

  addUtilities(buttons);
})
```

I expect to get the following whenever I use `@apply btn primary`:

```scss
.my-btn {
  @apply btn primary;
}
```

``` css
.my-btn {
  max-width: 12rem;
  min-height: 3.5rem;
  margin-top: 1rem;
  padding: .5rem 2rem;
  text-decoration: none;
  min-width: 6rem;
  text-align: center;
  border-radius: 1.25rem;
  background-color: #00d068;
  color: #fff;
  border: 2px solid #00d068;
}

.my-btn:hover {
  background-color: red
}
```

This is obviously not working, my question is whether what I am trying to do is possible or not.

Thanks

**Comment by estevanmaito** [comment] 2020-06-06 16:39
Duplicate of #1344 and #1599

**Comment by adamwathan** [comment] 2020-06-27 19:10
Your button classes in this case are not really utilities (they are what we'd call "components", and should be added using `addComponents`), and Tailwind's apply feature is very simple and only designed to work with utilities.

If you want more complex apply-like behavior like this, I would suggest the [postcss-extend-rule](https://github.com/csstools/postcss-extend-rule) plugin.

**Closed by adamwathan** 2020-06-27 19:10 UTC
