### ISSUE TITLE
No Ubuntu font for Ubuntu?

### ISSUE THREAD

**Issue by rilwis** [tailwindcss/tailwindcss#1921] opened 2020-06-13 16:28 UTC
Thanks for the great framework!

I'm building a site on Ubuntu and see that the default system font stack doesn't include "Ubuntu" font family, so it falls back to sans serif font.

I'd suggest adding Ubuntu font in the default system font stack to make it display beautifully on Ubuntu.

**Comment by estevanmaito** [comment] 2020-06-13 17:27
What browser (`navigator.userAgent`) and OS version are you using?

For me, Chrome renders Ubuntu while Firefox renders Arial.

Ubuntu 18.04.4, Chrome 80, Firefox 74

**Comment by rilwis** [comment] 2020-06-14 07:43
I'm using Firefox 69, Ubuntu 19.10 and it shows Arial. In the font list [here](https://tailwindcss.com/docs/font-family/), I don't see "Ubuntu" listed.

**Comment by estevanmaito** [comment] 2020-06-15 16:05
I think this is probably the desired effect on Firefox, as per this bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1469122

The closing comment that "resolved" the issue has this image: https://snipboard.io/1VfKwE.jpg

You can see that they acknowledge the difference between Chrome and Firefox, but doesn't seem to care: 

>So, I don't think there is a bug here, just normal differences between defaults on different platforms and browsers

---

But, I think we reached another point: when was Arial added to Ubuntu? Every mention to it that I found is from people asking how to add it, because, until today, I always thought it was a Microsoft font.

I will try this later, but I think that bringing "Noto Sans" (the default in most Linux systems I think) before Arial, would solve this, because the current rule assumes that Arial is not a Linux font.

**Comment by rilwis** [comment] 2020-06-16 01:27
@evenfrost I think you misunderstood. I didn't mean the font Arial is displayed differently on Chrome and Firefox on Ubuntu. I mean the font family declaration doesn't include the "Ubuntu" font (Ubuntu is a name of a font family).

The font stack for now is:

```
font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

which doesn't include "Ubuntu" font. So it falls back to "Arial", which is not what I want.

I'd suggest changing it to:

```
font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

**Comment by estevanmaito** [comment] 2020-06-16 03:26
I actually understood it right (and you tagged somebody else).

Just to make it clear, I'm trying to understand the bigger picture instead of just diving into adding a font that is used in only one distro.

I don't know any other Linux distro that packs Ubuntu, and the few that tried, realised it's a non-free font: [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4) and [Debian](https://bugs.launchpad.net/ubuntu-font-licence/+bug/769874).

That was my point.

Now I realised it's part of a bigger problem, probably introduced with https://github.com/tailwindcss/tailwindcss/pull/1326

Firefox does not support `system-ui` ([Can I Use](https://caniuse.com/#feat=font-family-system-ui)), while Chromium browsers do (that's why you see Ubuntu applied, not because it falls back to `sans-serif`). Without `system-ui`, you would be seeing Arial on both browsers on Ubuntu. (that's what Github and others are doing)

One of the points in the PR was

> Never having to update the string again

So I see 3 options that only @adamwathan can solve: remove `system-ui` so every browser can fallback to a common font (not only Ubuntu the OS), add Ubuntu before Arial or leave it as it is?

My preference is to remove `system-ui`, which would make everything look the same. But more importantly, I think the OP https://github.com/tailwindcss/tailwindcss/pull/1326 really misinterpreted and oversimplified the issue with chinese/japanese characters.

> the font they look at all day in that operating system.

![](https://infinnie.github.io/images/blog/bootstrap.png)

The OP says as if they were looking at the same native text, while the problem is that the font their system renders chinese/japanese is used to render english text. It's about looking at the same font, applied to the wrong language.

**Comment by rilwis** [comment] 2020-06-16 05:41
Thanks for the clarification. It's very useful to understand the `system-ui` between browsers.

**Comment by adamwathan** [comment] 2020-07-07 17:55
No plans to change this currently, but you can of course customize your font stack easily using your `tailwind.config.js` file 👍

**Closed by adamwathan** 2020-07-07 17:55 UTC
