### ISSUE TITLE
Conflict with utatti/perfect-scrollbar

### ISSUE THREAD

**Issue by leveloid** [tailwindcss/tailwindcss#466] opened 2018-05-14 23:12 UTC
I'm attempting to use this package:

https://github.com/utatti/perfect-scrollbar

and it seems Tailwind is interfering with the position of the scroll bar - causing `left: 0` to be added to the element during scroll.

I have both working correctly in another app using an older version of Tailwind (0.4.0) and I've narrowed the issue down to this line:

`@import "tailwindcss/utilities";`

but I'm stuck there. Any ideas?

**Comment by adamwathan** [comment] 2018-05-14 23:26
Looking here I don't see any classes that would conflict with Tailwind:

https://github.com/utatti/perfect-scrollbar/blob/master/css/perfect-scrollbar.css

I'd compare the CSS you are using for this package with Tailwind's output to look for duplicate class names. If there's a collision you can always use Tailwind's `prefix` option to prefix all Tailwind classes.

**Comment by adamwathan** [comment] 2018-05-14 23:27
Closing as not a bug or anything with Tailwind but happy to continue helping to troubleshoot.

**Closed by adamwathan** 2018-05-14 23:27 UTC

**Comment by leveloid** [comment] 2018-05-15 01:05
I agree with you that there are apparently no conflicts, but I switched on PurgeCSS to remove unused classes (whitelisting the CSS from perfect-scrollbar) and now everything works correctly... 🧐

**Comment by leveloid** [comment] 2018-05-15 03:09
Is there a way I can remove parts of the "tailwindcss/utilities" code to track down the offending line even further?

**Comment by adamwathan** [comment] 2018-05-15 10:19
Yep, disable individual modules in the modules section of your config file
by setting them to false one at a time 👍🏻

**Comment by leveloid** [comment] 2018-05-16 02:06
Ok - I've narrowed the issue down to any one of:

backgroundColors: ['responsive', 'hover'],
textStyle: ['responsive']

as in, removing **any one** of those three strings (2 responsive, 1 hover) fixes things.

Adding a prefix, setting important to true, or using a different separator doesn't change anything.

🤔

**Comment by leveloid** [comment] 2018-05-16 02:20
I found the above by first removing all the entries that only had `"responsive"` set.

After trying to first remove entries set to `"responsive, "hover"` removing a different combination of modules caused a fix.

This one has me stumped!
