### ISSUE TITLE
Sourecemap problems

### ISSUE THREAD

**Issue by RomkaLTU** [tailwindcss/tailwindcss#705] opened 2019-03-02 22:00 UTC
If I extract styles with apply at the beginning of class sourcemaps map for that class will not be available (no source). For example:

```
// This will not generate proper sourcemap
.something {
    @apply rounded border border-green text-sm;
    width: 142px;
    height: 40px;
}

// This will 
.something {
    width: 142px;
    height: 40px;
    @apply rounded border border-green text-sm;
}
```

**Comment by RomkaLTU** [comment] 2019-03-02 22:05
```
// This will not too
.something {
    @apply rounded border border-green text-sm;
}
```

**Comment by adamwathan** [comment] 2019-03-02 23:22
Can you share a project that reproduces? I just created a single CSS file with the following contents:

```css
.something {
    @apply rounded border border-green text-sm;
}
```

...and after processing with Tailwind it generated this source map:

```
{
  "version": 3,
  "sources": [
    "../tailwind.css",
    "<no source>"
  ],
  "names": [],
  "mappings": "AAAA;ECAA,sBAAA;EAAA,kBAAA;EAAA,sBAAA;EAAA,mBAAA;ADEA",
  "file": "tailwind.css",
  "sourcesContent": [
    ".something {\n  @apply rounded border border-green text-sm;\n}\n",
    null
  ]
}
```

...which pointed to the right source when tested in Chrome dev-tools.

**Comment by adamwathan** [comment] 2019-03-02 23:38
Here's my sample project:

https://github.com/adamwathan/tailwind-sourcemap-test

**Comment by adamwathan** [comment] 2019-03-16 18:22
Closing until a reproduction is provided.

**Closed by adamwathan** 2019-03-16 18:22 UTC

**Comment by pangolingo** [comment] 2019-08-21 22:51
Just wanted to chime in and say I've observed this same problem.
When `@apply` is at the top of the class, Chrome thinks all the class's styles are in `utilities.scss`. When `@apply` is at the bottom of the class, Chrome points to the correct source file (in my case, `_buttons.scss`.

Code:
```
.btn {
  @apply bg-brand-red;
  padding: 2rem;
```
Result:
<img width="587" alt="Screen Shot 2019-08-21 at 5 48 41 PM" src="https://user-images.githubusercontent.com/1423865/63473664-f1c75d80-c43b-11e9-9937-6cc6642ed5aa.png">

Code:
```
.btn {
  padding: 2rem;
  @apply bg-brand-red;
```
Result:
<img width="585" alt="Screen Shot 2019-08-21 at 5 49 22 PM" src="https://user-images.githubusercontent.com/1423865/63473706-0dcaff00-c43c-11e9-8545-27e3ee795657.png">

Not creating a repro because I'm working with v0.7.4 and this issue may be fixed in v1+.
