### ISSUE TITLE
Unable to override spacing with margin utilities

### ISSUE THREAD

**Issue by simon-tma** [tailwindcss/tailwindcss#2044] opened 2020-07-20 04:50 UTC
### Describe the problem:

When using the `space-x/y` utilities, it's impossible to override the applied margins using the margin utilities.

### Minimal reproduction:

```
<div class="flex flex-col space-y-4">
  <div>First div</div>
  <div class="my-8">Second div</div>
</div>
```

The second div still only has a top margin of 1rem, not the 2rem from `my-8`.

**Comment by eclectic-coding** [comment] 2020-07-20 19:28
That seems to be correct and I have confirmed. However, the role of `space-x/y` utilities are "controlling the space between child elements." I think since you are using `space-y-4` in the parent `div` it is higher in the cascade and has precedence.

**Comment by adamwathan** [comment] 2020-07-21 00:34
Duplicate of https://github.com/tailwindcss/tailwindcss/issues/1614

**Closed by adamwathan** 2020-07-21 00:34 UTC
