### ISSUE TITLE
[bug]: borderStyle cannot be overridden

### ISSUE THREAD

**Issue by maddhruv** [tailwindcss/tailwindcss#1360] opened 2020-02-04 14:23 UTC
the `borderStyle` property cannot be overridden as the util returns with just the static properties/theme - https://github.com/tailwindcss/tailwindcss/blob/master/src/plugins/borderStyle.js

```js
// config
borderStyle: {
  solid: "solid",
  dashed: "dashed"
},

// or

borderStyle: false
```
so, even when doing this, tailwind generates all the border styles and doesn't pick from the theme config.

**Comment by tlgreg** [comment] 2020-02-04 15:58
It's not just `˙borderStyle` but it's not a bug. Not every plugin's classes can be configured.

**Comment by maddhruv** [comment] 2020-02-04 16:23
are there any reasons for not making them configurable?

**Comment by adamwathan** [comment] 2020-03-11 13:18
Lots of CSS properties don't accept custom user values so we don't make those configurable. Like it wouldn't be useful to make `box-sizing` configurable for example.

If you want border style to be configurable for a specific use case though we can explore it — what are you actually looking to do?

**Comment by adamwathan** [comment] 2020-03-12 00:20
Going to close this as at least not a bug, if you'd like to be able to customize this don't hesitate to open a new issue as a feature request and detail the use case 👍🏻 Thanks!

**Closed by adamwathan** 2020-03-12 00:20 UTC
