### ISSUE TITLE
customized names for rule prefixes

### ISSUE THREAD

**Issue by axyz** [tailwindcss/tailwindcss#406] opened 2018-03-02 14:29 UTC
Hi,
would it be possible to customize the prefixes of the rules? Most of the file size comes from the big (and readable) selectors. While readability could be a good default choice, when size really matter would be nice to allow to have class names similar to tachyons.

Had a quick look on the option and this does not seem to be currently supported (correct me if I'm wrong)

If you think this kind of flexibility could fit in the project I could make a PR and discuss this further

**Comment by adamwathan** [comment] 2018-03-02 19:25
Hey! This isn't possible right now, maybe eventually but no concrete plans at the moment.

Duplicate of https://github.com/tailwindcss/tailwindcss/issues/102.

**Closed by adamwathan** 2018-03-02 19:25 UTC
