### ISSUE TITLE
Suggestion: Consolidate FONT and TEXT 

### ISSUE THREAD

**Issue by Montago** [tailwindcss/tailwindcss#1929] opened 2020-06-16 13:16 UTC
I know this might be legacy, but i dont get why we have FONT and TEXT classes. 

I'm not normally a designer so i have a hard time remembering whether to use TEXT or FONT when i need to change size, weight, color etc etc ... 

Why not scrap one and keep the other ? 

I suggest keeping FONT because that just makes sense :)

**Comment by estevanmaito** [comment] 2020-06-16 15:15
Possibly a duplicate of https://github.com/tailwindcss/tailwindcss/issues/1052

> No plans to unify this because text-light for example could be both a color and a weight in the same project.

**Comment by adamwathan** [comment] 2020-06-27 19:04
No plans to change this, see discussion here:

https://github.com/tailwindcss/tailwindcss/issues/1052#issuecomment-517666957

Thanks though.

**Closed by adamwathan** 2020-06-27 19:04 UTC
