### ISSUE TITLE
Cannot find module './cli/main' on npx tailwind init

### ISSUE THREAD

**Issue by danrocha** [tailwindcss/tailwindcss#812] opened 2019-04-01 06:22 UTC
Weird issue. Tailwind is installed in the local project only, not globally. I was using Tailwind 0.7.4 before in another project with no issues.

## Steps:

`npm install tailwindcss@next --save-dev`
```bash
+ tailwindcss@1.0.0-beta.4
added 37 packages from 53 contributors and audited 46930 packages in 28.314s
```
`npx tailwind init`
```bash
Cannot find module './cli/main'
```
I also checked the folder structure in `node_modules` and it all seems to be there. 

## Versions:

node v11.6.0
npm 6.8.0

macOS 10.14.4

**Comment by rowild** [comment] 2019-04-01 06:39
@danrocha I tried it, too, but get a positiv result.

node 11.10
npm 6.70.
macOS 10.13.6

I also udated npm to 6.9.0 and tested the setup with that version, and I again get positiv results... (which is: `Created Tailwind config file: tailwind.config.js`)

**Comment by danrocha** [comment] 2019-04-01 07:27
Any ideas on how could I experiment? 

The project is a simple Vue app, created with the Vue CLI3 `vue create` command.  Later tonight I could post a link to the repo... but nothing out of the ordinary there, all works fine except this command.

**Comment by rowild** [comment] 2019-04-01 07:37
What I did was just simply open my terminal, create and change-to a new folder, npm init, npm install tailswinscss, and tailwind init. Nothing more.

I'll try with Vue CLI and report back.

Do you have any idea, if the difference ein macOS systems could be the culprit? I mean to have read something about 10.14 being somewhat more strict in some regards. But I can't remember, if it was in the context of tailwind or something else so I might be wrong.

**Comment by rowild** [comment] 2019-04-01 07:56
I followed this Vue-cli setup:
`https://www.vuemastery.com/courses/real-world-vue-js/vue-cli/`

Then `npm i -D tailwindcss@next` and `npx tailwind init`.
The tailwind.config.js was created successfully.

Various things that come to my mind (probably totally unrelated to your problem):
- Is node installed via brew? (not recommended)
- Is there a `sudo` anywhere (e.g. for global installations)?

Sorry to not be of any better help here... hopefully somebody else has some more input!

**Comment by danrocha** [comment] 2019-04-02 04:58
Tried the same config as you (node 11.10, npm 6.7.0), then with latest (node 11.6, npm 6.9) but still no success. 
Ended up copying and pasting the config file...

will wait and see if the next update fixes it for me!

Thanks!

**Comment by adamwathan** [comment] 2019-04-26 16:24
Weird issue! Since we can't seem to reproduce this and no one else is running into it I'm going to close this for now, but if someone is able to reproduce I'd be happy to look into it more.

**Closed by adamwathan** 2019-04-26 16:24 UTC

**Comment by eoliphan** [comment] 2019-08-26 00:11
Also having this issue. 

Node v12.9.0
NPM 6.10.3
OS X 10.14.6

Just followed the basic install steps, everything was fine up to [step 3)(https://tailwindcss.com/docs/installation#3-create-your-tailwind-config-file-optional), and it created a default `tailwind.config.js`.  However, trying the build in step 4 fails, as does stuff like ` npx tailwind help build` with the same 

```
Cannot find module './cli/main'
Require stack:
- /Users/erichkoliphant/Dropbox/projects/sqdrepo/fuelingmain/node_modules/.bin/tailwind
```

**Comment by thelilmercoder** [comment] 2019-09-24 13:18
Also getting the error "Cannot find module ./cli/main' when I run the command 'npx tailwind build styles.css -o output.css'

This was all working two days ago and I've changed nothing.....

node v.8.10.0
npm v.6.11.3
ubuntu v.18.04.03

**Comment by nam-co** [comment] 2019-10-28 19:15
I tried "npm i npm-cli --save" and it seems to be working now, I also move the original css file to the root, the strange part is that Im also working inside of dropbox, maybe that's something that causes the problem

**Comment by SpecterPaul** [comment] 2020-01-02 20:16
Thank you
