### ISSUE TITLE
PurgeCSS option makes Tailwind work inappropriately

### ISSUE THREAD

**Issue by gokhantaskan** [tailwindcss/tailwindcss#1901] opened 2020-06-09 09:30 UTC
When I enable PurgeCSS option inside the tailwind config file, some of the classes do not work appropriately between HTML tags ie. `<div class="p-2"></div>` => p-2 class is not working but p-4 is working.

After converting `purge: enabled` to `false`, it works.

package.json
```js
"tailwindcss": "^1.4.6",
"vue": "^2.6.11"
```

tailwind.config.js
```js
module.exports = {
  purge: {
    enabled: true,
    content: [
      "./public/index.html",
      "./src/**/*.vue",
      "./src/**/*.js",
      "./src/**/*.ts"
    ]
  },
  ...
}
```

postcss.config.js
```js
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");

module.exports = {
  plugins: [
    tailwindcss({}),
    autoprefixer({})
  ]
};

```

main.scss
```css
@import "abstracts/variables";

@import "tailwindcss/base";
@import "tailwindcss/components";

@import
  "vendors/vue-good-table",
  ...
  "vendors/leaflet";

@import
  "base/typography",
  "base/base";

@import
  "components/menubar",
   ...
  "components/datepicker";

@import
  "layouts/empty-state",
   ...
  "layouts/table";

@import
  "pages/overview";

@import
  "tailwindcss/utilities";
```

**Comment by BjornLuG** [comment] 2020-06-09 14:19
It is very likely that `p-2` got accidentally purged. Make sure you're writing [purgable HTML](https://tailwindcss.com/docs/controlling-file-size/#writing-purgeable-html). Otherwise you can whitelist it as per [this example](https://tailwindcss.com/docs/controlling-file-size/#purgecss-options).

**Comment by adamwathan** [comment] 2020-06-12 11:19
Can you create a project that reproduces the issue and link to it? It will be much easier to diagnose the root cause that way 👍

**Comment by adamwathan** [comment] 2020-06-27 19:36
Closing since there has been no follow up since asking for the reproduction so I'm assuming you figured out your issue 👍

**Closed by adamwathan** 2020-06-27 19:36 UTC
