### ISSUE TITLE
hover:break-normal not working with truncate

### ISSUE THREAD

**Issue by ifaniqbal** [tailwindcss/tailwindcss#1349] opened 2020-01-31 06:50 UTC
I already add `'hover'` in `wordBreak` variant, but it didn't work, the text still truncated.
- Version 1.1.4

**Comment by adamwathan** [comment] 2020-01-31 12:42
The class definitely gets generated in the CSS as expected so I think this is just an expectation mismatch. `break-normal` doesn't really have anything to do with truncation, it has to do with whether words should be broken mid-word to wrap if the parent element is too narrow for the text.

Here's an example of what it does:

https://tailwind.run/DFuyui

Happy to help you with your underlying problem either way if you'd like to post a reproduction, closing this issue though since it's not a bug with how `hover:break-normal` works.

**Closed by adamwathan** 2020-01-31 12:42 UTC
