### ISSUE TITLE
Compiled base: propertyIgnoredDueToDisplay warning

### ISSUE THREAD

**Issue by shiftgeist** [tailwindcss/tailwindcss#1765] opened 2020-05-13 15:49 UTC
```
Property is ignored due to the display. With 'display: block', vertical-align should not be used.
```

![image](https://user-images.githubusercontent.com/30648730/81834711-9b59fc00-9541-11ea-930d-9cd0e6d358d8.png)

Refered mdn page: https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

On line 574 of the compiled `base.css` (tw version 1.4.6).

![image](https://user-images.githubusercontent.com/30648730/81834951-f390fe00-9541-11ea-9f41-4692362959da.png)

**Comment by xdega** [comment] 2020-05-23 16:51
I can confirm that I am also encountering this issue.

**Comment by adamwathan** [comment] 2020-05-23 17:58
Duplicate of https://github.com/tailwindcss/tailwindcss/pull/1221

**Closed by adamwathan** 2020-05-23 17:58 UTC

**Comment by sameer240704** [comment] 2023-09-06 16:27
Can anyone provide a solution to this please

**Comment by MOHAMMED-THE-SWE** [comment] 2024-02-19 11:42
>You can fix it by changing display: block to display: inline-block;

---

### like this 
`
object {
  display: inline-block;
  /* 1 */
  vertical-align: middle;
  /* 2 */
}
`
