### ISSUE TITLE
text-opacity does not work with inheritance from parent

### ISSUE THREAD

**Issue by jenstornell** [tailwindcss/tailwindcss#2047] opened 2020-07-20 11:43 UTC
This code works:

```html
<div class="text-white text-opacity-50">Faded</div>
```

This code does not work (opacity is not set):

```html
<div class="text-white">
  <div class="text-opacity-50">Not faded</div>
</div>
```

It's not useful to use a parent in this particular example but when there are many children it can be helpful to use the parent.

**Comment by adamwathan** [comment] 2020-07-20 13:16
Duplicate of #1780, has been documented since:

https://tailwindcss.com/docs/text-opacity/#usage

![image](https://user-images.githubusercontent.com/4323180/87941797-aa8d8680-ca69-11ea-87ca-1c1dfbb5538d.png)

**Closed by adamwathan** 2020-07-20 13:16 UTC

**Comment by cybervaldez** [comment] 2020-10-12 10:28
Is there a way to stop the variable from being present? (e.g: rgba(160, 174, 192, var(--text-opacity))? It's bloating twin.macro which i'm using to do property animations with. I would prefer to just see rgb(160, 174, 192)

**Comment by frederikhors** [comment] 2023-04-10 10:18
> Duplicate of #1780, has been documented since:
> 
> https://tailwindcss.com/docs/text-opacity/#usage
> 
> ![image](https://user-images.githubusercontent.com/4323180/87941797-aa8d8680-ca69-11ea-87ca-1c1dfbb5538d.png)

This warning in docs is vanished, or am I wrong?
