### ISSUE TITLE
Tailwind 1.01 installation with web pack not working

### ISSUE THREAD

**Issue by mauricebalde** [tailwindcss/tailwindcss#937] opened 2019-05-24 13:34 UTC
Since 1.01 you can't compile it down, 
nom expects still a config file that supposed to be optional.
And even if you compose the tailwind.js it is looking for, things don't work as many classes still are missing.

**Comment by adamwathan** [comment] 2019-05-24 13:48
Please provide a GitHub repo that reproduces the problem so I can show you what you need to fix.

Tailwind 1.0 works perfectly fine with webpack, and without a config file.

Here is an example repo with everything set up and working correctly:

https://github.com/tailwindcss/webpack-starter

Happy to help troubleshoot but closing the issue since it is user error.

**Closed by adamwathan** 2019-05-24 13:48 UTC
