### ISSUE TITLE
Different height for input type date & text with the same styles 

### ISSUE THREAD

**Issue by thearyanahmed** [tailwindcss/tailwindcss#1819] opened 2020-05-25 11:08 UTC
Hello,
I'm facing a problem with input types, the height seems to change for ```<input type="date" ... />```

I'm using the code from [tailwind's form examples](https://tailwindcss.com/components/forms/#app). 

Code (notice the 'type' attribute)

```
// type text
<input type="text" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-city" placeholder="Albuquerque">

// type date
<input type="date" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-city" placeholder="Albuquerque">

```

![image](https://user-images.githubusercontent.com/20617352/82807738-3213aa80-9eaa-11ea-8238-fe299baf2d64.png)

It is sort of breaking the design.

**Comment by estevanmaito** [comment] 2020-05-25 12:32
I copied and pasted your code here https://codepen.io/estevanmaito/pen/BaoEpzY?editors=1000

And couldn't reproduce it. Does it happen in this CodePen also for you?

Could you give us more details? Browser version (user agent), are you using any plugin? What is the style around the input?

**Comment by thearyanahmed** [comment] 2020-05-25 12:59
Yes, also happened to codepen, maybe perhaps I made a mistake, here is the full code

[https://codepen.io/thearyanahmed/pen/bGVJgvm?editors=1010](https://codepen.io/thearyanahmed/pen/bGVJgvm?editors=1010) 

Using 
Chrome Version 81.0.4044.138 (Official Build) (64-bit) 
mac OS catalina (version 10.15.4 ), 
Nuxt js ^2.0.0
Vue ^2.6.11

Also, I'm not overriding any CSS, not custom styles. Also, have the default tailwind.config.js 
Same for safari.

**Comment by estevanmaito** [comment] 2020-05-25 13:52
It's a Chrome issue with status of **WontFix**: https://bugs.chromium.org/p/chromium/issues/detail?id=417606

It explains why I didn't see it: on Firefox it runs ok.

The only solution is to give every input an explicit height, like `h-10` or `h-12`.

**Comment by thearyanahmed** [comment] 2020-05-25 14:08
I see, thanks, another note, I also had this issue with safari.

**Closed** 2020-05-25 14:08 UTC

**Comment by estevanmaito** [comment] 2020-05-25 14:38
Sorry. I should've said *Chromium* browsers. It will affect Chrome, Safari, Edge, Opera, etc...
